### ISSUE TITLE
Save fields?

### ISSUE THREAD

**Issue by jklymak** [takah29/2d-fluid-simulator#4]
Hi - this looks to be a pretty nice package.  I was considering using it for teaching purposes.  

Is there any way to get the fields written to disk for students to perform analysis on them (say the state variables if nothing higher order?). If not, I can dig deeper and try to figure out how to save the arrays being plotted.  Thanks!

**Comment by takah29** [comment]
Hi! Thank you for looking at the code.

I've added a simple feature to dump the field. It might not be exactly what you intended, but I hope it will be useful for reference.

During execution, if you press the 'd' key, the numpy array of the field will be saved as output/step_<step_number>.npz in the same location as main.py.

For example, you can view the field data as an image using matplotlib like this. Keep in mind that the data structure of the field remains the same, so you need to rotate it 90 degrees when displaying it as an image.

```python
import numpy as np
import matplotlib.pyplot as plt

# fields has keys v (velocity), p (pressure), and dye
fields = np.load("output/step_<step_number>.npz")

print(fields["v"].shape)

# Display the x component of the velocity field
plt.imshow(np.rot90(fields["v"][:, :, 0]))
plt.show()
```

**Comment by jklymak** [comment]
Thanks for this meant to say that it was very helpful
